version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POETRY_INSTALL_OPTIONS: ""
        DJANGO_SETTINGS_MODULE: "cocoon_news_project.settings"
    ports:
      - "8000:8000"
    volumes:
      - .:/django
    entrypoint:
      - ./docker/entrypoint.sh
